name: exercise_e2
description: Exercise E2, course IDATA2503 Mobile applications
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  intl: ^0.17.0
